struct BufferData
{
	float3 position : ATTR0;
	float2 texCoord : ATTR1;
	float3 normal	: ATTR2;
};

struct VertexToFragment
{
	float4 position : POSITION;
	float2 texCoord : TEXCOORD0;
};

VertexToFragment main( BufferData IN,
					   uniform float4x4 modelViewProjection )
{	
	VertexToFragment OUT;
	
	OUT.position = mul( modelViewProjection, float4( IN.position, 1.0 ) ); // float4( IN.position / 2, 1.0 ); // 
	OUT.texCoord = IN.texCoord;
	//OUT.color = IN.color;
	
	return OUT;	
}
